### PR TITLE
[7.11][ML] Assorted time series modelling improvements

### PR DESCRIPTION
**Pull request by tveasey**
Backport #1614.

### CODE REVIEW

**Comment by tveasey** [comment]
retest

**Comment by droberts195** [comment]
`std::size` is C++17 - that's why it doesn't work in 7.x, where we're still on C++14.  I guess some compilers might not be following what's in each standard exactly though, hence letting it work ahead of time.

**Comment by tveasey** [comment]
retest

**Comment by tveasey** [comment]
retest

**Pull request merged**
