### PR TITLE
[ML] Upgrade Boost to version 1.77

### PR DESCRIPTION
**Pull request by droberts195**
We have been using Boost version 1.71 for a long time
now, and it's good to upgrade occasionally.

Version 1.77 contains support for macOS on ARM, so
upgrading to this version avoids the need to hack the
Boost build files.

### CODE REVIEW

**Comment by droberts195** [comment]
retest

**Comment by droberts195** [comment]
For Linux we need to allow extra system calls, because since https://github.com/boostorg/filesystem/commit/e2e4b85ee07101dcbb25f4785af3a757c3156fa8 `boost::filesystem::unique_path` uses the `getrandom` syscall on Linux, and since https://github.com/boostorg/filesystem/commit/3e8c8b15f940145481c5eb73bc6c108b5bace1da `boost::filesystem::create_directories` uses the `statx` syscall on Linux.

**Comment by droberts195** [comment]
retest

**Review by tveasey — APPROVED** [review]
LGTM

**Pull request merged**
