### PR TITLE
[ML] Adding CI for macOS on ARM

### PR DESCRIPTION
**Pull request by droberts195**
This change adds coverage for macOS on ARM to CI.

There are 3 parts to this:

1. Download the pre-built 3rd party dependencies at the
   beginning of the build.  Unlike Linux builds which can
   get these dependencies by building in a Docker container,
   the macOS CI machines need to get them via a more
   primitive mechanism.
2. Adjust the Jenkins CI shell script to account for the
   possibility of having to build natively on macOS as well
   as in Docker on Linux.
3. Switch to the newer S3 API from Amazon.  The old S3 API
   didn't work in Java 9 or above, which we worked around by
   ensuring Java 8 was installed on the CI workers.  But
   that's not possible for macOS on ARM, so it's finally
   forced an upgrade.

### CODE REVIEW

**Comment by droberts195** [comment]
Before merging I will run CI again on this PR once the new macOS ARM Jenkins workers are online.

**Comment by droberts195** [comment]
retest

**Comment by droberts195** [comment]
retest

**Comment by droberts195** [comment]
retest

**Review by edsavage — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
retest

**Review by tveasey — APPROVED** [review]
LGTM

**Pull request merged**
