### PR TITLE
[ML] Write actual thread settings after pytorch process starts

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
When the `pytorch_inference` process starts, we validate the given
thread settings and adjust them if necessary. This commit changes
the process to write the actual thread settings back to ES.

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci

**Comment by dimitris-athanasiou** [comment]
retest

**Comment by dimitris-athanasiou** [comment]
retest

**Pull request merged**
