### PR TITLE
[ML] Change outlier detection feature influence format to nested object

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
This changes the format of `feature_influence` for outlier detection so
that the feature name is not part of the field name. This helps reduce
field explosion in the results index.

Feature influence is now an array with nested objects. Each of them contains
the `feature_name` and the `influence` value.

### CODE REVIEW

**Review by valeriy42 — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci

**Comment by dimitris-athanasiou** [comment]
test

**Comment by dimitris-athanasiou** [comment]
retest

**Pull request merged**
