### PR TITLE
[ML] Add a notebook incrementally training DGA with sunburst domains

### PR DESCRIPTION
**Pull request by tveasey**
This adds a notebook incrementally training DGA model with around 1300 sunburst domains and testing on a hold out set of around 300 domains. We get accuracy before of 0 (although in our shipped model this was closer to 0.5 so not sure of the source of the discrepancy). After updating this model we get test accuracy 0.96.

I also fix a typo I spotted in the progress monitoring phase name.

### CODE REVIEW

**Comment by tveasey** [comment]
The failing unit test is tracked in #2033.

**Review by valeriy42 — APPROVED** [review]
Looks good.

Nit: could you maybe rename the notebook into `03-dga-sunbirst` for consistency?

**Comment by tveasey** [comment]
> Nit: could you maybe rename the notebook into 03-dga-sunbirst for consistency?

Agreed: [see](https://github.com/elastic/ml-cpp/pull/2056/commits/20edc1ec0f041109532177ccf74e648ad15ab3d7).

**Comment by tveasey** [comment]
retest

**Pull request merged**
